/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.com.popcorn.refund;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RefundEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2026620140893720419L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RefundEvent\",\"namespace\":\"avro.com.popcorn.refund\",\"fields\":[{\"name\":\"firstName\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"The first name of the customer requesting the refund\"},{\"name\":\"lastName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"The last name of the customer requesting the refund\",\"default\":null}],\"version\":1}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RefundEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RefundEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RefundEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RefundEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RefundEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RefundEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RefundEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RefundEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RefundEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The first name of the customer requesting the refund */
  private java.lang.Object firstName;
  /** The last name of the customer requesting the refund */
  private java.lang.String lastName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RefundEvent() {}

  /**
   * All-args constructor.
   * @param firstName The first name of the customer requesting the refund
   * @param lastName The last name of the customer requesting the refund
   */
  public RefundEvent(java.lang.Object firstName, java.lang.String lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstName;
    case 1: return lastName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstName = value$; break;
    case 1: lastName = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The first name of the customer requesting the refund
   */
  public java.lang.Object getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * The first name of the customer requesting the refund
   * @param value the value to set.
   */
  public void setFirstName(java.lang.Object value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The last name of the customer requesting the refund
   */
  public java.lang.String getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * The last name of the customer requesting the refund
   * @param value the value to set.
   */
  public void setLastName(java.lang.String value) {
    this.lastName = value;
  }

  /**
   * Creates a new RefundEvent RecordBuilder.
   * @return A new RefundEvent RecordBuilder
   */
  public static avro.com.popcorn.refund.RefundEvent.Builder newBuilder() {
    return new avro.com.popcorn.refund.RefundEvent.Builder();
  }

  /**
   * Creates a new RefundEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RefundEvent RecordBuilder
   */
  public static avro.com.popcorn.refund.RefundEvent.Builder newBuilder(avro.com.popcorn.refund.RefundEvent.Builder other) {
    if (other == null) {
      return new avro.com.popcorn.refund.RefundEvent.Builder();
    } else {
      return new avro.com.popcorn.refund.RefundEvent.Builder(other);
    }
  }

  /**
   * Creates a new RefundEvent RecordBuilder by copying an existing RefundEvent instance.
   * @param other The existing instance to copy.
   * @return A new RefundEvent RecordBuilder
   */
  public static avro.com.popcorn.refund.RefundEvent.Builder newBuilder(avro.com.popcorn.refund.RefundEvent other) {
    if (other == null) {
      return new avro.com.popcorn.refund.RefundEvent.Builder();
    } else {
      return new avro.com.popcorn.refund.RefundEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RefundEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RefundEvent>
    implements org.apache.avro.data.RecordBuilder<RefundEvent> {

    /** The first name of the customer requesting the refund */
    private java.lang.Object firstName;
    /** The last name of the customer requesting the refund */
    private java.lang.String lastName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.com.popcorn.refund.RefundEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing RefundEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.com.popcorn.refund.RefundEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'firstName' field.
      * The first name of the customer requesting the refund
      * @return The value.
      */
    public java.lang.Object getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * The first name of the customer requesting the refund
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public avro.com.popcorn.refund.RefundEvent.Builder setFirstName(java.lang.Object value) {
      validate(fields()[0], value);
      this.firstName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * The first name of the customer requesting the refund
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'firstName' field.
      * The first name of the customer requesting the refund
      * @return This builder.
      */
    public avro.com.popcorn.refund.RefundEvent.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * The last name of the customer requesting the refund
      * @return The value.
      */
    public java.lang.String getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * The last name of the customer requesting the refund
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public avro.com.popcorn.refund.RefundEvent.Builder setLastName(java.lang.String value) {
      validate(fields()[1], value);
      this.lastName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * The last name of the customer requesting the refund
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastName' field.
      * The last name of the customer requesting the refund
      * @return This builder.
      */
    public avro.com.popcorn.refund.RefundEvent.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RefundEvent build() {
      try {
        RefundEvent record = new RefundEvent();
        record.firstName = fieldSetFlags()[0] ? this.firstName :  defaultValue(fields()[0]);
        record.lastName = fieldSetFlags()[1] ? this.lastName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RefundEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RefundEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RefundEvent>
    READER$ = (org.apache.avro.io.DatumReader<RefundEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (firstName == null ? 0 : firstName.hashCode());
    result = 31 * result + (lastName == null ? 0 : lastName.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof RefundEvent)) {
      return false;
    }
    RefundEvent other = (RefundEvent) o;
    if (!java.util.Objects.equals(this.firstName, other.firstName)) {
      return false;
    }
    if (!java.util.Objects.equals(this.lastName, other.lastName)) {
      return false;
    }
    return true;
  }
}










